# This is a config yaml file for FreeSurfer BIDS App
# Input datasets configuration
input_datasets:
    BIDS:
        required_files:
            - "anat/*_T1w.nii*"
        is_zipped: false
        origin_url: "${BIDS_ORIGIN}"
        path_in_babs: inputs/data/BIDS
    NIDM:
        required_files:
            - "nidm.ttl"
        is_zipped: false
        origin_url: "${NIDM_ORIGIN}"
        path_in_babs: inputs/data/NIDM
# Arguments passed to the application inside the container
bids_app_args:
    "$SUBJECT_SELECTION_FLAG": "--participant_label"
    --fs-license-file: "/orcd/scratch/bcs/001/yibei/prettymouth_babs/license.txt"
    --skip-bids-validation: ""
    # Note: NIDM will be generated automatically if NIDM/ directory exists
singularity_args:
    - --no-home
    - --writable-tmpfs
# Output foldername(s) to be zipped:
zip_foldernames:
    freesurfer-nidm_bidsapp: "0-1-0"
# How much cluster resources it needs:
cluster_resources:
    interpreting_shell: "/bin/bash"
    customized_text: |
        #SBATCH --partition=condo
        #SBATCH --qos=condo
        #SBATCH --account=csd841
        #SBATCH --cpus-per-task=8
        #SBATCH --mem=24G
        #SBATCH --time=03:30:00
        #SBATCH --job-name=fs-nidm_bidsapp_${RUN_DATE}
# Necessary commands to be run first:
script_preamble: |
    source ~/.bashrc
    micromamba activate babs
    module load singularitypro/3.11
# Where to run the jobs:
job_compute_space: "${COMPUTE_SPACE}"
required_files:
    "$INPUT_DATASET_#1":
        - "anat/*_T1w.nii*"
# Alert messages that might be found in log files of failed jobs:
alert_log_messages:
    stdout:
        - "ERROR:"
        - "Cannot allocate memory"
        - "mris_curvature_stats: Could not open file"
        - "Numerical result out of range"
        - "FreeSurfer failed"
        - "recon-all: error"
        - "NIDM conversion failed"
